SELECT HLOD.DEFINITION_KEY,
       HLOD.DESCRIPTION,
       HLOD.HLL_DEFINITION_SOURCE,
       COUNT(*) CANTIDAD_LOGS_IGUALES -- OVER (PARTITION BY HLOD.DEFINITION_KEY, HLOD.DESCRIPTION, HLOD.HLL_DEFINITION_SOURCE) CANTIDAD_LOGS_IGUALES
FROM ADELIA.HLL_LOG_OBJECT_DEFINITION HLOD
GROUP BY HLOD.DEFINITION_KEY, HLOD.DESCRIPTION, HLOD.HLL_DEFINITION_SOURCE
;


SELECT HLU.HLL_USE_CLASS,
       LISTAGG(TRIM(HLC.DESCRIPTION), ' - ') WITHIN GROUP (ORDER BY TRIM(HLC.DESCRIPTION)) CATEGORIAS
FROM ADELIA.HL_LOG_USE HLU
INNER JOIN ADELIA.HL_LOG_CATEGORY HLC ON HLC.OBJECTID = HLU.LOG_CATEGORY
GROUP BY HLU.HLL_USE_CLASS