--de las ord desde enero a junio monto total por concepto.

--code cpto, desc cpto, 1, 2,3,4,5,6
--404-00,    asing fliar, 5342823.23, 584946251., 54654

SELECT L.DESCRIPCION, 
       CL.CODE CODIGO_CONCEPTO, 
       CL.DESCRIPTION DESCRIPCION_CONCEPTO, 
       SUM(ACL.MONTO) MONTO_TOTAL
       --(ACL.MONTO) MONTO_TOTAL
FROM ADELIA.CONCEPTO_LIQUIDACION CL
INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.CONCEPTO_LIQ = CL.OBJECTID
INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.OBJECTID = ACL.LIQUIDACION_CARGO
INNER JOIN ADELIA.LIQUIDACION L ON L.OBJECTID = LC.LIQUIDACION
INNER JOIN ADELIA.PROCESO_LIQUIDACION PL ON PL.OBJECTID = L.PROCESO_LIQ
WHERE 1=1
      AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
      AND PL.PERIODO BETWEEN TO_DATE('01-01-2023', 'DD-MM-YYYY') AND TO_DATE('01-06-2023', 'DD-MM-YYYY')
GROUP BY L.DESCRIPCION, CL.CODE, CL.DESCRIPTION



SELECT L.DESCRIPCION, 
       CL.CODE CODIGO_CONCEPTO, 
       CL.DESCRIPTION DESCRIPCION_CONCEPTO, 
       --SUM(ACL.MONTO) MONTO_TOTAL
       --(ACL.MONTO) MONTO_TOTAL
       --case when cl.CODE like '502%' and to_number(ac.CANTIDAD) > 1 then to_number(ac.CANTIDAD) else null end
       SUM(CASE WHEN PL.PERIODO = TO_DATE('01-01-2023', 'DD-MM-YYYY') THEN ACL.MONTO ELSE 0 END) MONTO_ENERO,
       SUM(CASE WHEN PL.PERIODO = TO_DATE('01-02-2023', 'DD-MM-YYYY') THEN ACL.MONTO ELSE 0 END) MONTO_FEBRERO
FROM ADELIA.CONCEPTO_LIQUIDACION CL
INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.CONCEPTO_LIQ = CL.OBJECTID
INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.OBJECTID = ACL.LIQUIDACION_CARGO
INNER JOIN ADELIA.LIQUIDACION L ON L.OBJECTID = LC.LIQUIDACION
INNER JOIN ADELIA.PROCESO_LIQUIDACION PL ON PL.OBJECTID = L.PROCESO_LIQ
WHERE 1=1
      AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
      AND PL.PERIODO IN (TO_DATE('01-01-2023', 'DD-MM-YYYY'), TO_DATE('01-02-2023', 'DD-MM-YYYY'))
GROUP BY L.DESCRIPCION, CL.CODE, CL.DESCRIPTION


SELECT CL.CODE CODIGO_CONCEPTO, 
       CL.DESCRIPTION DESCRIPCION_CONCEPTO, 
       SUM(MONTO1.MONTO_ENERO) MONTO_ENERO,
       SUM(MONTO2.MONTO_FEBRERO) MONTO_FEBRERO
       --(ACL.MONTO) MONTO_TOTAL
       --case when cl.CODE like '502%' and to_number(ac.CANTIDAD) > 1 then to_number(ac.CANTIDAD) else null end
       --SUM(MONTO1.MONTO_ENERO)
FROM ADELIA.CONCEPTO_LIQUIDACION CL
INNER JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                    ACL.MONTO MONTO_ENERO 
                    FROM ADELIA.PROCESO_LIQUIDACION PL
                    INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                    INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                    INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                    WHERE 1=1
                          AND PL.PERIODO IN (TO_DATE('01-01-2023', 'DD-MM-YYYY'))
                          AND UPPER(L.DESCRIPCION) LIKE 'ORD%' ) MONTO1 ON MONTO1.CONCEPTO = CL.OBJECTID
INNER JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                    ACL.MONTO MONTO_FEBRERO 
                    FROM ADELIA.PROCESO_LIQUIDACION PL
                    INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                    INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                    INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                    WHERE 1=1
                          AND PL.PERIODO IN (TO_DATE('01-02-2023', 'DD-MM-YYYY'))
                          AND UPPER(L.DESCRIPCION) LIKE 'ORD%' ) MONTO2 ON MONTO2.CONCEPTO = CL.OBJECTID
GROUP BY CL.CODE, CL.DESCRIPTION
      --AND PL.PERIODO IN (TO_DATE('01-01-2023', 'DD-MM-YYYY'), TO_DATE('01-02-2023', 'DD-MM-YYYY'))


SELECT CL.CODE CODIGO_CONCEPTO, 
       CL.DESCRIPTION DESCRIPCION_CONCEPTO, 
       NVL(MONTO1.MONTO_ENERO, 0) MONTO_ENERO,
       NVL(MONTO2.MONTO_FEBRERO, 0) MONTO_FEBRERO,
       NVL(MONTO3.MONTO_MARZO, 0) MONTO_MARZO,
       NVL(MONTO4.MONTO_ABRIL, 0) MONTO_ABRIL,
       NVL(MONTO5.MONTO_MAYO, 0) MONTO_MAYO,
       NVL(MONTO6.MONTO_JUNIO, 0) MONTO_JUNIO
       FROM ADELIA.CONCEPTO_LIQUIDACION CL
        --ENERO
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_ENERO 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-01-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO1 ON MONTO1.CONCEPTO = CL.OBJECTID
        --FEBRERO
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_FEBRERO 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-02-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO2 ON MONTO2.CONCEPTO = CL.OBJECTID
        --MARZO
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_MARZO 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-03-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO3 ON MONTO3.CONCEPTO = CL.OBJECTID
        --ABRIL
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_ABRIL 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-04-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO4 ON MONTO4.CONCEPTO = CL.OBJECTID
         --MAYO
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_MAYO 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-05-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO5 ON MONTO5.CONCEPTO = CL.OBJECTID
         --JUNIO
        LEFT JOIN ( SELECT ACL.CONCEPTO_LIQ CONCEPTO,
                            SUM(ACL.MONTO) MONTO_JUNIO 
                            FROM ADELIA.PROCESO_LIQUIDACION PL
                            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
                            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
                            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
                            WHERE 1=1
                                  AND PL.PERIODO IN (TO_DATE('01-06-2023', 'DD-MM-YYYY'))
                                  AND UPPER(L.DESCRIPCION) LIKE 'ORD%'
                            GROUP BY ACL.CONCEPTO_LIQ ) MONTO6 ON MONTO6.CONCEPTO = CL.OBJECTID
WHERE NVL(MONTO1.MONTO_ENERO, 0) 
      + NVL(MONTO2.MONTO_FEBRERO,0) 
      + NVL(MONTO3.MONTO_MARZO,0) 
      + NVL(MONTO4.MONTO_ABRIL,0) 
      + NVL(MONTO5.MONTO_MAYO,0) 
      + NVL(MONTO6.MONTO_JUNIO, 0) > 0 