--Comparativo de asignaciones familiares entre junio y julio.
--dni, apellido y nombre, escalafon, cpto, cant_junio, monto_junio, cant_julio, monto_julio

12345678, 414-00, 2, 9820, 0, 0
12345678, 406-00, 2, 9820, 2, 9820
12345678, 407-00, 0, 0, 1, 5000
12345678, 414-00, 2, 9820, 1, 5000

'4%' hijo

SELECT P.NRO_DOCUMENTO DNI, 
        P.APELLIDO || ' ' || P.NOMBRE AGENTE, 
        TRIM(E.CODE) || '-' || E.DESCRIPTION ESCALAFON,
        TRIM(PR.CODE) || '-' || PR.DESCRIPTION CONCEPTO,
        PR.PERIODO,
        PR.CANTIDAD,
        SUM(PR.MONTO) JUNIO,
        PR2.PERIODO,
        PR2.CANTIDAD, 
        SUM(PR2.MONTO) JULIO        
FROM ADELIA.PERSONA P
INNER JOIN ADELIA.AGENTE A ON A.PERSONA = P.OBJECTID
INNER JOIN ADELIA.CARGO C ON C.AGENTE = A.OBJECTID
INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.CARGO = C.OBJECTID
inner join ADELIA.DEFINICION_CARGO DC on C.DEFINICION_CARGO = DC.OBJECTID
inner join ADELIA.POF_SAF PF on PF.NODO_ESTRUCTURA = C.NODOPOF_ACTUAL
inner join ADELIA.ESCALAFON E on C.ESCALAFON = E.OBJECTID
INNER JOIN ADELIA.LIQUIDACION L ON LC.LIQUIDACION = L.OBJECTID
INNER JOIN (SELECT PL.PERIODO PERIODO, 
                    L.OBJECTID LIQUIDACION,
                    ACL.CANTIDAD CANTIDAD,
                    ACL.MONTO,
                    CL.CODE,
                    CL.DESCRIPTION                    
            FROM ADELIA.PROCESO_LIQUIDACION PL
            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
            INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
            WHERE PL.PERIODO = TO_DATE('01/06/2023','DD/MM/YYYY')) PR ON PR.LIQUIDACION = L.OBJECTID
left JOIN (SELECT PL.PERIODO PERIODO, 
                    L.OBJECTID LIQUIDACION,
                    ACL.CANTIDAD CANTIDAD,
                    ACL.MONTO,
                    CL.CODE,
                    CL.DESCRIPTION                    
            FROM ADELIA.PROCESO_LIQUIDACION PL
            INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
            INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
            WHERE PL.PERIODO = TO_DATE('01/07/2023','DD/MM/YYYY')) PR2 ON PR2.LIQUIDACION = L.OBJECTID              
WHERE TRIM(PR.CODE) LIKE '4%' 
AND P.NRO_DOCUMENTO = '17911465'
GROUP BY P.NRO_DOCUMENTO, P.APELLIDO, P.NOMBRE, E.CODE, E.DESCRIPTION, PR.CODE, PR.DESCRIPTION, PR.PERIODO,PR.CANTIDAD, PR2.CANTIDAD, PR2.PERIODO;


SELECT P.NRO_DOCUMENTO DNI, 
        P.APELLIDO || ' ' || P.NOMBRE AGENTE, 
        TRIM(E.CODE) || '-' || E.DESCRIPTION ESCALAFON,
        TRIM(PR.CODE) || '-' || PR.DESCRIPTION CONCEPTO,
        PR.PERIODO,
        PR.CANTIDAD,
        SUM(PR.MONTO) JUNIO,
        PR2.PERIODO,
        PR2.CANTIDAD, 
        SUM(PR2.MONTO) JULIO,        
        pr.cantidad - pr2.cantidad dif_cant,
        SUM(PR2.MONTO) - SUM(PR.MONTO) dif_monto
FROM ADELIA.PERSONA P
INNER JOIN ADELIA.AGENTE A ON A.PERSONA = P.OBJECTID
INNER JOIN ADELIA.CARGO C ON C.AGENTE = A.OBJECTID
inner join ADELIA.ESCALAFON E on C.ESCALAFON = E.OBJECTID
INNER JOIN (SELECT P.NRO_DOCUMENTO,
                    ACL.MONTO,
                    PL.PERIODO,
                    ACL.CANTIDAD,
                    CL.CODE,
                    CL.DESCRIPTION
            FROM ADELIA.PERSONA P
            INNER JOIN ADELIA.AGENTE A ON A.PERSONA = P.OBJECTID
            INNER JOIN ADELIA.CARGO C ON C.AGENTE = A.OBJECTID
            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.CARGO = C.OBJECTID
            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
            INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
            INNER JOIN ADELIA.LIQUIDACION L ON LC.LIQUIDACION = L.OBJECTID 
            INNER JOIN ADELIA.PROCESO_LIQUIDACION PL ON PL.OBJECTID = L.PROCESO_LIQ
            WHERE CL.CODE LIKE '4%' 
            --AND P.NRO_DOCUMENTO = '17911465'
            AND PL.PERIODO = TO_DATE('01/07/2023','DD/MM/YYYY') ) PR ON P.NRO_DOCUMENTO = PR.NRO_DOCUMENTO
left JOIN (SELECT P.NRO_DOCUMENTO,
                    ACL.MONTO,
                    PL.PERIODO,
                    ACL.CANTIDAD,
                    CL.CODE,
                    CL.DESCRIPTION
            FROM ADELIA.PERSONA P
            INNER JOIN ADELIA.AGENTE A ON A.PERSONA = P.OBJECTID
            INNER JOIN ADELIA.CARGO C ON C.AGENTE = A.OBJECTID
            INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.CARGO = C.OBJECTID
            INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
            INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
            INNER JOIN ADELIA.LIQUIDACION L ON LC.LIQUIDACION = L.OBJECTID 
            INNER JOIN ADELIA.PROCESO_LIQUIDACION PL ON PL.OBJECTID = L.PROCESO_LIQ
            WHERE CL.CODE LIKE '4%' 
            --AND P.NRO_DOCUMENTO = '17911465'
            AND PL.PERIODO = TO_DATE('01/07/2023','DD/MM/YYYY')) PR2 ON PR2.NRO_DOCUMENTO = P.NRO_DOCUMENTO              
--WHERE TRIM(PR.CODE) LIKE '4%' 
--AND P.NRO_DOCUMENTO = '17911465'
GROUP BY P.NRO_DOCUMENTO,PR.CODE, PR.DESCRIPTION, P.APELLIDO, P.NOMBRE, E.CODE, E.DESCRIPTION, PR.PERIODO,PR.CANTIDAD, PR2.CANTIDAD, PR2.PERIODO;


SELECT PL.PERIODO PERIODO, 
       L.OBJECTID LIQUIDACION,
       ACL.CANTIDAD CANTIDAD,
       ACL.MONTO
FROM ADELIA.PROCESO_LIQUIDACION PL
INNER JOIN ADELIA.LIQUIDACION L ON L.PROCESO_LIQ = PL.OBJECTID
INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.LIQUIDACION = L.OBJECTID
INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
WHERE PL.PERIODO = TO_DATE('01/06/2023','DD/MM/YYYY')


SELECT P.NRO_DOCUMENTO
FROM ADELIA.PERSONA P
INNER JOIN ADELIA.AGENTE A ON A.PERSONA = P.OBJECTID
INNER JOIN ADELIA.CARGO C ON C.AGENTE = A.OBJECTID
INNER JOIN ADELIA.LIQUIDACION_CARGO LC ON LC.CARGO = C.OBJECTID
INNER JOIN ADELIA.APLICACION_CONCEPTO_LIQ ACL ON ACL.LIQUIDACION_CARGO = LC.OBJECTID
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION CL ON CL.OBJECTID = ACL.CONCEPTO_LIQ
INNER JOIN ADELIA.LIQUIDACION L ON LC.LIQUIDACION = L.OBJECTID 
INNER JOIN ADELIA.PROCESO_LIQUIDACION PL ON PL.OBJECTID = L.PROCESO_LIQ
WHERE CL.CODE LIKE '4%' 
AND P.NRO_DOCUMENTO = '17911465'
AND PL.PERIODO BETWEEN TO_DATE('01/07/2023','DD/MM/YYYY') AND SYSDATE 







SELECT P1.NRO_DOCUMENTO DNI, 
       P1.APELLIDO || ' ' || P1.NOMBRE AGENTE, 
       TRIM(E.CODE) || '-' || E.DESCRIPTION ESCALAFON, 
       TRIM(PR.CODE) || '-' || PR.DESCRIPTION CONCEPTO, 
       PR.PERIODO, 
       PR.CANTIDAD, 
       SUM(PR.MONTO) JUNIO, 
       PR2.PERIODO, 
       PR2.CANTIDAD, 
       SUM(PR2.MONTO) JULIO, 
       pr.cantidad - pr2.cantidad dif_cant, 
       SUM(PR2.MONTO) - SUM(PR.MONTO) dif_monto 
  FROM ADELIA.PERSONA P1 
       INNER JOIN ADELIA.AGENTE A1 
          ON A1.PERSONA = P1.OBJECTID 
       INNER JOIN ADELIA.CARGO C1 
          ON C1.AGENTE = A1.OBJECTID 
       INNER JOIN ADELIA.ESCALAFON E 
          ON C1.ESCALAFON = E.OBJECTID 
       INNER JOIN (SELECT /*+ USE_NL(PL1,L1,CL1,ACL1,LC1,C2,A2) */ P2.NRO_DOCUMENTO, 
                          ACL1.MONTO, 
                          PL1.PERIODO, 
                          ACL1.CANTIDAD, 
                          CL1.CODE, 
                          CL1.DESCRIPTION 
                     FROM ADELIA.PERSONA P2, 
                          ADELIA.AGENTE A2, 
                          ADELIA.CARGO C2, 
                          ADELIA.LIQUIDACION_CARGO LC1, 
                          ADELIA.APLICACION_CONCEPTO_LIQ ACL1, 
                          ADELIA.CONCEPTO_LIQUIDACION CL1, 
                          ADELIA.LIQUIDACION L1, 
                          ADELIA.PROCESO_LIQUIDACION PL1 
                    WHERE CL1.CODE LIKE '4%' 
                      AND PL1.PERIODO = TO_DATE('01/07/2023', 'DD/MM/YYYY') 
                      AND PL1.OBJECTID = L1.PROCESO_LIQ 
             AND LC1.LIQUIDACION = L1.OBJECTID 
             AND CL1.OBJECTID = ACL1.CONCEPTO_LIQ 
             AND ACL1.LIQUIDACION_CARGO = LC1.OBJECTID 
             AND LC1.CARGO = C2.OBJECTID 
             AND C2.AGENTE = A2.OBJECTID 
             AND A2.PERSONA = P2.OBJECTID) PR 
          ON P1.NRO_DOCUMENTO = PR.NRO_DOCUMENTO 
       LEFT JOIN (SELECT P3.NRO_DOCUMENTO, 
                         ACL2.MONTO, 
                         PL2.PERIODO, 
                         ACL2.CANTIDAD, 
                         CL2.CODE, 
                         CL2.DESCRIPTION 
                    FROM ADELIA.PERSONA P3, 
                         ADELIA.AGENTE A3, 
                         ADELIA.CARGO C3, 
                         ADELIA.LIQUIDACION_CARGO LC2, 
                         ADELIA.APLICACION_CONCEPTO_LIQ ACL2, 
                         ADELIA.CONCEPTO_LIQUIDACION CL2, 
                         ADELIA.LIQUIDACION L2, 
                         ADELIA.PROCESO_LIQUIDACION PL2 
                   WHERE CL2.CODE LIKE '4%' 
                     AND PL2.PERIODO = TO_DATE('01/07/2023', 'DD/MM/YYYY') 
                     AND PL2.OBJECTID = L2.PROCESO_LIQ 
            AND LC2.LIQUIDACION = L2.OBJECTID 
            AND CL2.OBJECTID = ACL2.CONCEPTO_LIQ 
            AND ACL2.LIQUIDACION_CARGO = LC2.OBJECTID 
            AND LC2.CARGO = C3.OBJECTID 
            AND C3.AGENTE = A3.OBJECTID 
            AND A3.PERSONA = P3.OBJECTID) PR2 
         ON PR2.NRO_DOCUMENTO = P1.NRO_DOCUMENTO 
 GROUP BY P1.NRO_DOCUMENTO, PR.CODE, PR.DESCRIPTION, P1.APELLIDO, P1.NOMBRE, E.CODE, E.DESCRIPTION, PR.PERIODO, PR.CANTIDAD, PR2.CANTIDAD, PR2.PERIODO;