--INSPECCIONAR TODOS LOS CODIGOS DE ADELIA
SELECT *
FROM (
SELECT EXPRESION AS CODIGO, 'VARIABLE FORMULA' origen, a.CODE nombre 
FROM ADELIA.VARIABLE_FORMULA_LIQUIDACION a
UNION ALL
SELECT CALCULO AS CODIGO, 'FORMULA CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT TO_CLOB(OBJETO_LIQUIDADO) AS CODIGO, 'OBJETO LIQUIDADO CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT TO_CLOB(CONDICION_EJECUCION) AS CODIGO, 'CONDICION EJECUCION CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT BLOB_TO_CLOB(SOURCE) AS CODIGO, 'DEFINICION DE CONSULTAS' origen, A.DESCRIPTION nombre
FROM ADELIA.QUERY_DEFINITION a
) --WHERE upper(CODIGO) like upper('%font%bold%')
WHERE REGEXP_LIKE(UPPER(CODIGO), 'TIENE_OBRA_SOC_AGENTE_122302|TIENE_OBRA_SOC_AGENTE_003207|TIENE_OBRA_SOC_AGENTE_001102|TIENE_AFIL_OS_NO_DOSEP_AGENTE')
ORDER BY 2

/*
A REVISAR
502-36
502-00
502-02
502-04
502-32

FORMULA ORIGINAL
TIENE_OBRA_SOCIAL_122302
TIENE_OBRA_SOCIAL_003207
TIENE_OBRA_SOCIAL_001102
TIENE_AFIL_SIMPLE_OS_NO_DOSEP

FORMULA MODIFICADA
TIENE_OBRA_SOC_AGENTE_122302 
TIENE_OBRA_SOC_AGENTE_003207 
TIENE_OBRA_SOC_AGENTE_001102
TIENE_AFIL_OS_NO_DOSEP_AGENTE


*/

