--INSPECCIONAR TODOS LOS CODIGOS DE ADELIA
SELECT *
FROM (
SELECT EXPRESION AS CODIGO, 'VARIABLE FORMULA' origen, a.CODE nombre 
FROM ADELIA.VARIABLE_FORMULA_LIQUIDACION a
UNION ALL
SELECT CALCULO AS CODIGO, 'FORMULA CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT TO_CLOB(OBJETO_LIQUIDADO) AS CODIGO, 'OBJETO LIQUIDADO CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT TO_CLOB(CONDICION_EJECUCION) AS CODIGO, 'CONDICION EJECUCION CONCEPTO' origen, A.ORDEN_EJECUCION || ' - ' ||C.CODE ||' '||C.DESCRIPTION  nombre
FROM ADELIA.FORMULA_LIQUIDACION a
INNER JOIN ADELIA.CONCEPTO_LIQUIDACION C ON a.concepto_liquidacion = C.OBJECTID
UNION ALL
SELECT BLOB_TO_CLOB(SOURCE) AS CODIGO, 'DEFINICION DE CONSULTAS' origen, A.DESCRIPTION nombre
FROM ADELIA.QUERY_DEFINITION a
) WHERE upper(CODIGO) like upper('%font%bold%')
ORDER BY 2