--LOGS INACTIVOS QUE TIENEN UN DUPLICADO CON LA MISMA CLASE ACTIVADO Y NO SE PUEDEN BORRAR
SELECT HLU.OBJECTID,
       HLU.HLL_USE_CLASS CLASE,
       HLU.HLL_USE_SELECTOR SELECTOR,
       HLU.HHL_USE_VARIABLE_GETTE VARIABLES,
       HLU.DESCRIPTION DESCRIPCION, 
       HLU.HLL_IS_ACTIVE_USE ACTIVO,  
       HLU.HLL_DESCRIPTION_SOURCE       
FROM ADELIA.HL_LOG_USE HLU
WHERE 1=1
      AND (TRIM(HLU.HLL_USE_CLASS)) IN (SELECT TRIM(HLU.HLL_USE_CLASS)
                                  FROM ADELIA.HL_LOG_USE HLU
                                  WHERE 1=1
                                        AND HLU.HLL_IS_ACTIVE_USE = 1)
      AND HLU.HLL_IS_ACTIVE_USE = 0
ORDER BY HLU.HLL_USE_CLASS, HLU.HLL_USE_SELECTOR


--LOGS INACTIVOS QUE NO TIENEN UN DUPLICADO Y QUE TAMPOCO SE PUEDEN BORRAR
SELECT HLU.OBJECTID,
       HLU.HLL_USE_CLASS CLASE,
       HLU.HLL_USE_SELECTOR SELECTOR,
       HLU.HHL_USE_VARIABLE_GETTE VARIABLES,
       HLU.DESCRIPTION DESCRIPCION, 
       HLU.HLL_IS_ACTIVE_USE ACTIVO,  
       HLU.HLL_DESCRIPTION_SOURCE       
FROM ADELIA.HL_LOG_USE HLU
WHERE 1=1
      AND (HLU.HLL_USE_CLASS) NOT IN (SELECT HLU.HLL_USE_CLASS
                                  FROM ADELIA.HL_LOG_USE HLU
                                  WHERE 1=1
                                        AND HLU.HLL_IS_ACTIVE_USE = 1)
      AND HLU.HLL_IS_ACTIVE_USE = 0
ORDER BY HLU.HLL_USE_CLASS, HLU.HHL_USE_VARIABLE_GETTE


--LISTADO DE LOGS INACTIVOS CON SU DUPLICADO ACTIVO
SELECT INACTIVOS.OBJECTID ID_01,
       INACTIVOS.HLL_USE_CLASS CLASE_01,
       INACTIVOS.HLL_USE_SELECTOR SELECTOR_01,
       INACTIVOS.HLL_IS_ACTIVE_USE ACTIVO_01,
       ACTIVOS.OBJECTID ID_02,
       ACTIVOS.HLL_USE_CLASS CLASE_02,
       ACTIVOS.HLL_USE_SELECTOR SELECTOR_02,
       ACTIVOS.HLL_IS_ACTIVE_USE ACTIVO_02
FROM (SELECT *      
       FROM ADELIA.HL_LOG_USE HLU
       WHERE 1=1
             AND (HLU.HLL_USE_CLASS) IN (SELECT HLU.HLL_USE_CLASS
                                          FROM ADELIA.HL_LOG_USE HLU
                                          WHERE 1=1
                                                AND HLU.HLL_IS_ACTIVE_USE = 1)
              AND HLU.HLL_IS_ACTIVE_USE = 0
) INACTIVOS
INNER JOIN ADELIA.HL_LOG_USE ACTIVOS ON ACTIVOS.HLL_USE_CLASS = INACTIVOS.HLL_USE_CLASS AND TRIM(ACTIVOS.HLL_USE_SELECTOR) = TRIM(INACTIVOS.HLL_USE_SELECTOR) 
WHERE 1=1
      AND ACTIVOS.HLL_IS_ACTIVE_USE = 1
ORDER BY INACTIVOS.HLL_USE_CLASS, INACTIVOS.HLL_USE_SELECTOR

--CONTAR LOGS REPETIDOS

SELECT *
FROM ADELIA.HL_LOG_USE HLU
WHERE 1=1
      AND TRIM(HLU.HLL_USE_SELECTOR) = 'addRetroactivo:'
      --AND HLU.HLL_IS_ACTIVE_USE = 0
ORDER BY HLU.HLL_USE_CLASS

SELECT TRIM(HLU.HLL_USE_CLASS) CLASE,
       TRIM(HLU.HLL_USE_SELECTOR) SELECTOR,
       COUNT(*) CANTIDAD
FROM ADELIA.HL_LOG_USE HLU
WHERE 1=1
      AND TRIM(HLU.HLL_USE_CLASS) IN (
          SELECT TRIM(HLU.HLL_USE_CLASS)
          FROM ADELIA.HL_LOG_USE HLU
          WHERE 1=1
                AND HLU.HLL_IS_ACTIVE_USE = 1
      )
      AND HLU.HLL_IS_ACTIVE_USE = 0
GROUP BY TRIM(HLU.HLL_USE_SELECTOR), TRIM(HLU.HLL_USE_CLASS)
HAVING COUNT(*) > 1
ORDER BY CANTIDAD DESC;